### ISSUE TITLE
Commit fail, Broker: Unknown member

### ISSUE THREAD

**Issue by Kelthan** [KonstantinCodes/messenger-kafka#28]
Hi,
With the new release 0.12 we encountered the following exception with our consumer:
```
INFO      [app] Offset topic=messages partition=0 offset=2 to be committed asynchronously.
%4|1606832093.118|COMMITFAIL|rdkafka#consumer-10| [thrd:main]: Offset commit (manual) failed for 1/1 partition(s): Broker: Unknown member: messages[0]@3(Broker: Unknown member)
```

With the v0.11 we didn't have any  problems, our consumer configuration was not changed and look like this:
```
   messages_consumer:
        dsn: '%env(KAFKA_DSN_CONSUMER)%'
        serializer: messenger.transport.symfony_serializer
        options:
          commitAsync: true
          receiveTimeout: 10000
          topic:
            name: 'messages'
          kafka_conf:
            enable.auto.offset.store: 'false'
            group.id: 'messages-consumer'
          topic_conf:
            auto.offset.reset: 'earliest'
        retry_strategy:
          max_retries: 0
```

Any idea of what may cause the problem ?

Thank you :)
