### ISSUE TITLE
Configuration property rebalance_cb is a consumer property and will be ignored by this producer instance

### ISSUE THREAD

**Issue by karrakoliko** [KonstantinCodes/messenger-kafka#85]
When i run phpunit test, i see this error:

```
%4|1726260229.083|CONFWARN|rdkafka#producer-1| [thrd:app]: Configuration property rebalance_cb is a consumer property and will be ignored by this producer instance
```

I dont pass rebalance_cb to producer transport, my config loooks like this:

```
framework:
  messenger:
    transports:
      producer:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        # serializer: App\Infrastructure\Messenger\MySerializer
        options:
          flushTimeout: 10000
          flushRetries: 5
          topic:
            name: 'test'
      consumer:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        # serializer: App\Infrastructure\Messenger\MySerializer
        options:
          commitAsync: true
          receiveTimeout: 100
          topic:
            name: "test"
          kafka_conf:
            enable.auto.offset.store: 'false'
            group.id: 'karrakoliko' # should be unique per consumer
          topic_conf:
            auto.offset.reset: 'earliest'
    routing:
      App\Message\HelloWorldMessage: producer
```

I think that error appears because of how rebalance callback passed at [KafkaTransportFactory](https://github.com/KonstantinCodes/messenger-kafka/blob/bd977b7670bbd0b838225cf34db8a8176e2bd53e/src/Messenger/KafkaTransportFactory.php#L62)
